//======================================================================
// QUYỀN LỰC BÓNG TỐI - SERVER LOGIC (FULL BOT THÔNG MINH)
//======================================================================

const express = require('express');
const http = require('http');
const path = require('path');
const { Server } = require("socket.io");

const app = express();
const server = http.createServer(app);
const io = new Server(server, { pingInterval: 10000, pingTimeout: 5000 });
const publicPath = path.join(__dirname, 'public');
app.use(express.static(publicPath));
const rooms = {};

const CHAOS_DURATION = 30; const DECREE_REVEAL_DELAY = 5000; const WIN_SCORE = 15; const LOSE_SCORE = -15;

// [NÂNG CẤP] Kích hoạt và lập trình logic cho các Sắc Lệnh phức tạp
const DECREES = {
    "NGAY_NHAN_DOI": { name: "Ngày Nhân Đôi", description: "Tất cả điểm cộng và trừ trong vòng này sẽ được nhân đôi!", getPointMultiplier: () => 2 },
    "GIO_GIOI_NGHIEM": { name: "Giờ Giới Nghiêm", description: "Vòng này cấm mọi hành vi Thách Đấu và Ghép Đội.", isChaosDisabled: true },
    "NGAY_PHAN_XET_DAO_NGUOC": { name: "Ngày Phán Xét Đảo Ngược", description: "Phe có NHIỀU phiếu hơn sẽ là phe chiến thắng!", determineWinner: (c, t) => (c === t ? null : (c > t ? 'Cống Hiến' : 'Tham Nhũng')) },
    "THUE_THAN": { name: "Thuế Thân", description: "Cuối vòng, người cao điểm nhất -2 điểm, số điểm đó được cộng cho người thấp điểm nhất.", endOfRoundEffect: (gs, results, pointMultiplier) => { const h = getPlayersByScore(gs.players, 'highest'); const l = getPlayersByScore(gs.players, 'lowest'); if (h.length > 0 && l.length > 0 && h[0].id !== l[0].id) { const tax = 2 * pointMultiplier; h.forEach(p => p.score -= tax); l.forEach(p => p.score += tax * h.length / l.length); results.messages.push(`📜 **Thuế Thân** được áp dụng!`); } } },
    "LOI_THI_THAM_CUA_QUY": { name: "Lời Thì Thầm Của Quỷ", description: "Hoán đổi lựa chọn của mọi người theo vòng tròn.", isChaosDisabled: true, onReveal: (gs, io, roomCode) => { const a = gs.players.filter(p => !p.isDefeated && p.chosenAction); if (a.length < 2) return; const c = a.map(p => p.chosenAction); for (let i = 0; i < a.length; i++) { a[i].chosenAction = c[(i === 0) ? a.length - 1 : i - 1]; } io.to(roomCode).emit('actionsSwapped', { message: "😈 Lựa chọn của mọi người đã bị hoán đổi!" }); } },
    "AMNESIA_DAY": { name: "Ngày Mất Trí", description: "Người thấp điểm nhất hoán đổi lựa chọn của 2 người.", onReveal: (gs, io, roomCode, drawerId) => {
        const drawer = gs.players.find(p => p.id === drawerId);
        if (drawer.isBot) handleBotAmnesia(roomCode, drawerId);
        else { gs.phase = 'special_action'; io.to(drawerId).emit('promptAmnesiaAction', { players: gs.players.map(p => ({ id: p.id, name: p.name })) }); io.to(roomCode).except(drawerId).emit('logMessage', { type: 'warning', message: `🧠 Đang chờ ${drawer.name} thực hiện quyền năng...`}); }
    } },
    "DAU_TRUONG_LA_MA": { name: "Đấu Trường La Mã", description: "Người thấp điểm nhất chọn 2 Đấu Sĩ. Khán giả đặt cược điểm.", onReveal: (gs, io, roomCode, drawerId) => {
        const drawer = gs.players.find(p => p.id === drawerId);
        if (drawer.isBot) handleBotRomanArena(roomCode, drawerId);
        else { gs.phase = 'special_action'; io.to(drawerId).emit('promptRomanArenaAction', { players: gs.players.map(p => ({ id: p.id, name: p.name })) }); io.to(roomCode).except(drawerId).emit('logMessage', { type: 'warning', message: `⚔️ Đang chờ ${drawer.name} chọn ra 2 Đấu Sĩ...`}); }
    } },
    "DI_SAN_CUA_KE_THANG": { name: "Di Sản Của Kẻ Thắng", description: "Người thắng vòng này được chọn Sắc Lệnh cho vòng sau từ 3 lá ngẫu nhiên." },
    "NGAY_SONG_TRUNG": { name: "Ngày Song Trùng", description: "Người bốc được sẽ bốc thêm 1 Sắc Lệnh nữa, áp dụng cả 2 trong vòng này." },
};

const ALL_DECREE_IDS = Object.keys(DECREES);

// ... các hàm logic khác giữ nguyên ...
function createGameState(players) { const gameState = { players: players.map(p => ({ ...p, score: 0, chosenAction: null, isDefeated: false, disconnected: false })), currentRound: 0, winScore: WIN_SCORE, loseScore: LOSE_SCORE, phase: 'waiting', roundData: {}, decreeDeck: [], decreeDiscard: [], nextDecree: null }; shuffleDecreeDeck(gameState); return gameState; }
function shuffleDecreeDeck(gs) { gs.decreeDeck = [...ALL_DECREE_IDS]; for (let i = gs.decreeDeck.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [gs.decreeDeck[i], gs.decreeDeck[j]] = [gs.decreeDeck[j], gs.decreeDeck[i]]; } gs.decreeDiscard = []; }
function startNewRound(roomCode) { const room = rooms[roomCode]; if (!room || !room.gameState) return; const gs = room.gameState; gs.currentRound++; gs.phase = 'choice'; gs.players.forEach(p => { if (!p.isDefeated) p.chosenAction = null; }); gs.roundData = { decrees: [], chaosActionTaken: false, chaosResult: null, chaosTimer: null, drawerId: null, votesToSkip: new Set(), choiceTimer: null }; io.to(roomCode).emit('newRound', { roundNumber: gs.currentRound, players: gs.players.map(({ id, name, score, isDefeated, disconnected }) => ({ id, name, score, isDefeated, disconnected })), duration: 30 }); gs.roundData.choiceTimer = setTimeout(() => { gs.players.forEach(p => { if (!p.chosenAction && !p.isDefeated) { const choices = ['Cống Hiến', 'Tham Nhũng', 'Phiếu Trống']; const randomChoice = choices[Math.floor(Math.random() * choices.length)]; handlePlayerChoice(roomCode, p.id, randomChoice); } }); }, 30 * 1000); triggerBotChoices(roomCode); }
function revealDecreeAndContinue(roomCode) { const gs = rooms[roomCode].gameState; gs.phase = 'decree'; if (gs.currentRound === 1) { io.to(roomCode).emit('logMessage', { type: 'info', message: "Vòng 1 không có Sắc Lệnh." }); startChaosPhase(roomCode); return; } if (gs.decreeDeck.length < 3) shuffleDecreeDeck(gs); const lowest = getPlayersByScore(gs.players, 'lowest'); const drawer = lowest[Math.floor(Math.random() * lowest.length)]; gs.roundData.drawerId = drawer.id; let decreesToReveal = []; if (gs.nextDecree) { decreesToReveal.push(gs.nextDecree); gs.nextDecree = null; } else { const decreeId = gs.decreeDeck.pop(); gs.decreeDiscard.push(decreeId); decreesToReveal.push(decreeId); if (decreeId === 'NGAY_SONG_TRUNG') { const secondDecreeId = gs.decreeDeck.pop(); gs.decreeDiscard.push(secondDecreeId); decreesToReveal.push(secondDecreeId); } } gs.roundData.decrees = decreesToReveal.map(id => ({ ...DECREES[id], id })); io.to(roomCode).emit('decreeRevealed', { drawerName: drawer.name, decrees: gs.roundData.decrees.map(d => ({ name: d.name, description: d.description })) }); setTimeout(() => { let continueToChaos = true; for (const decree of gs.roundData.decrees) { if (decree.onReveal) { decree.onReveal(gs, io, roomCode, drawer.id); if (gs.phase === 'special_action') { continueToChaos = false; break; } } } if (continueToChaos) startChaosPhase(roomCode); }, DECREE_REVEAL_DELAY); }
function startChaosPhase(roomCode) { const gs = rooms[roomCode]?.gameState; if (!gs) return; if (gs.roundData.decrees.some(d => d.isChaosDisabled)) { endChaosPhase(roomCode, `Một Sắc Lệnh đã cấm Giai Đoạn Hỗn Loạn!`); return; } gs.phase = 'chaos'; io.to(roomCode).emit('chaosPhaseStarted', { duration: CHAOS_DURATION }); gs.roundData.chaosTimer = setTimeout(() => endChaosPhase(roomCode, "Hết giờ, không có hành động nào diễn ra."), CHAOS_DURATION * 1000); triggerBotChaosAction(roomCode); }
function endChaosPhase(roomCode, message) { const gs = rooms[roomCode]?.gameState; if (!gs || gs.roundData.chaosActionTaken) return; gs.roundData.chaosActionTaken = true; gs.phase = 'reveal_pending'; clearTimeout(gs.roundData.chaosTimer); io.to(roomCode).emit('chaosActionResolved', { message }); setTimeout(() => calculateScoresAndEndRound(roomCode), 3000); }
function calculateScoresAndEndRound(roomCode) { const gs = rooms[roomCode]?.gameState; if (!gs) return; gs.phase = 'reveal'; const { decrees, chaosResult } = gs.roundData; const results = { messages: [], scoreChanges: {}, isDraw: false, winner: null, roundWinners: [] }; let pointMultiplier = 1; decrees.forEach(d => { if(d.getPointMultiplier) pointMultiplier *= d.getPointMultiplier(); }); const active = gs.players.filter(p => !p.isDefeated); if (active.length === 0) return; const votes = { 'Cống Hiến': 0, 'Tham Nhũng': 0, 'Phiếu Trống': 0 }; active.forEach(p => { if (p.chosenAction) votes[p.chosenAction]++; }); if (chaosResult?.success && chaosResult.actionType === 'teamup') { if (votes[chaosResult.actionToReduce] > 0) { votes[chaosResult.actionToReduce]--; results.messages.push("🤝 Ghép Đội thành công, một phiếu được loại bỏ!"); } } const { 'Cống Hiến': c, 'Tham Nhũng': t, 'Phiếu Trống': pt } = votes; const totalVotes = c + t + pt; let isDraw = false; if ((c === t && c > 0) || (active.length > 1 && (c === totalVotes || t === totalVotes)) || (pt > 0 && c === 0 && t === 0) || (pt > 0 && totalVotes === pt + c && t === 0) || (pt > 0 && totalVotes === pt + t && c === 0)) isDraw = true; let winner = null; if (isDraw) results.messages.push("⚖️ Kết quả: **HÒA**!"); else { const reverseDecree = decrees.find(d => d.id === 'NGAY_PHAN_XET_DAO_NGUOC'); winner = reverseDecree ? (c > t ? 'Cống Hiến' : 'Tham Nhũng') : (c < t ? 'Cống Hiến' : 'Tham Nhũng'); if (reverseDecree) results.messages.push(`📜 Sắc lệnh 'Ngày Phán Xét Đảo Ngược' có hiệu lực!`); results.messages.push(`Phe **${winner}** đã chiến thắng!`); } active.forEach(p => { let change = 0; if (isDraw) change = pt > 0 ? (p.chosenAction === 'Phiếu Trống' ? -1 : 1) : -1; else if (p.chosenAction === winner) { change = 2; results.roundWinners.push(p.id); } else if (p.chosenAction === 'Phiếu Trống') change = 3; const final = change * pointMultiplier; p.score += final; results.scoreChanges[p.id] = final; }); gs.roundData.lastScoreChanges = results.scoreChanges; decrees.forEach(d => d.endOfRoundEffect?.(gs, results, pointMultiplier)); io.to(roomCode).emit('roundResult', { players: gs.players, results, finalVoteCounts: votes }); handlePostRoundEvents(roomCode, results.roundWinners); }
function getPlayersByScore(players, type) { const a = players.filter(p => !p.isDefeated && !p.disconnected); if (a.length === 0) return []; const s = a.map(p => p.score); const c = type === 'highest' ? Math.max(...s) : Math.min(...s); return a.filter(p => p.score === c); }
function handlePlayerChoice(roomCode, playerId, choice) { const gs = rooms[roomCode]?.gameState; if (!gs || gs.phase !== 'choice') return; const p = gs.players.find(p => p.id === playerId); if (p && !p.chosenAction) { p.chosenAction = choice; io.to(roomCode).emit('playerChose', playerId); } if (gs.players.filter(p => !p.isDefeated).every(p => p.chosenAction)) { clearTimeout(gs.roundData.choiceTimer); revealDecreeAndContinue(roomCode); } }
function handleChaosAction(roomCode, initiatorId, targetId, actionType, guess = null) { const gs = rooms[roomCode]?.gameState; if (!gs || gs.phase !== 'chaos' || gs.roundData.chaosActionTaken) return; const i = gs.players.find(p => p.id === initiatorId), t = gs.players.find(p => p.id === targetId); if (!i || !t) return; let msg = ""; let multi = 1; gs.roundData.decrees.forEach(d => {if(d.getPointMultiplier) multi *= d.getPointMultiplier();}); if (actionType === 'challenge') { const success = guess === t.chosenAction; msg = `🔥 **${i.name}** đã Thách Đấu **${t.name}** và ${success ? "đoán **ĐÚNG**" : "đoán **SAI**"}!`; const change = 2 * multi; if (success) { i.score += change; t.score -= change; } else { i.score -= change; t.score += change; } } else if (actionType === 'teamup') { const success = i.chosenAction === t.chosenAction; msg = `🤝 **${i.name}** đã Ghép Đội với **${t.name}** và ${success ? "**thành công**" : "**thất bại**"}!`; if (success) gs.roundData.chaosResult = { actionType, success, actionToReduce: i.chosenAction }; else i.score -= multi; } endChaosPhase(roomCode, msg); }
function triggerRandomEvent(roomCode) { const gs = rooms[roomCode]?.gameState; if (!gs || Math.random() > 0.20) return; const events = ['avenger', 'treasury_empty']; const randomEvent = events[Math.floor(Math.random() * events.length)]; let message = ""; if (randomEvent === 'avenger') { let maxLoser = null; let maxLoss = 0; for (const id in gs.roundData.lastScoreChanges) { if (gs.roundData.lastScoreChanges[id] < maxLoss) { maxLoss = gs.roundData.lastScoreChanges[id]; maxLoser = gs.players.find(p => p.id === id); } } if (maxLoser) { maxLoser.score += 2; message = `⚔️ **Thích Khách Báo Thù!** ${maxLoser.name} bị trừ nhiều điểm nhất và được ban thưởng 2 điểm an ủi!`; } } else if (randomEvent === 'treasury_empty') { gs.players.forEach(p => p.score--); message = `📉 **Ngân Khố Rỗng Tuếch!** Do khủng hoảng, tất cả người chơi bị trừ 1 điểm!`; } if (message) { io.to(roomCode).emit('logMessage', { type: 'warning', message }); io.to(roomCode).emit('updateScores', gs.players.map(p => ({ id: p.id, score: p.score }))); } }
function triggerBotChoices(roomCode) { rooms[roomCode]?.gameState?.players.forEach(p => { if (p.isBot && !p.isDefeated) setTimeout(() => { if (!p.chosenAction) { let choice; switch(p.personality) { case 'aggressive': choice = Math.random() < 0.7 ? 'Tham Nhũng' : 'Cống Hiến'; break; case 'cautious': choice = Math.random() < 0.75 ? 'Cống Hiến' : 'Phiếu Trống'; break; default: choice = ['Cống Hiến', 'Tham Nhũng', 'Phiếu Trống'][Math.floor(Math.random() * 3)]; } handlePlayerChoice(roomCode, p.id, choice); } }, Math.random() * 2000 + 1500); }); }
function triggerBotChaosAction(roomCode) { const gs = rooms[roomCode]?.gameState; if (!gs) return; const bots = gs.players.filter(p => p.isBot && !p.isDefeated); const targets = gs.players.filter(p => !p.isDefeated); if (bots.length === 0 || targets.length < 2) return; bots.forEach(bot => { setTimeout(() => { if (gs.phase !== 'chaos' || gs.roundData.chaosActionTaken) return; const candidates = targets.filter(p => p.id !== bot.id); if (candidates.length === 0) return; const target = candidates[Math.floor(Math.random() * candidates.length)]; const actionProbability = bot.personality === 'aggressive' ? 0.6 : (bot.personality === 'cautious' ? 0.3 : 0.4); if (Math.random() < actionProbability) { const actionType = (bot.personality === 'cautious' && Math.random() < 0.8) ? 'teamup' : 'challenge'; if (actionType === 'challenge') { const guess = ['Cống Hiến', 'Tham Nhũng', 'Phiếu Trống'][Math.floor(Math.random() * 3)]; handleChaosAction(roomCode, bot.id, target.id, 'challenge', guess); } else { handleChaosAction(roomCode, bot.id, target.id, 'teamup'); } } else if (Math.random() < 0.5) { socket.emit('playerVotedToSkip', roomCode, bot.id); } }, Math.random() * 10000 + 5000); }); }
function handleBotAmnesia(roomCode, botId) { const gs = rooms[roomCode].gameState; const bot = gs.players.find(p => p.id === botId); io.to(roomCode).emit('logMessage', { type: 'warning', message: `🧠 ${bot.name} (Bot) đang sử dụng quyền năng của **Ngày Mất Trí**...` }); setTimeout(() => { const activePlayers = gs.players.filter(p => !p.isDefeated); if (activePlayers.length < 2) { startChaosPhase(roomCode); return; } let p1Idx = Math.floor(Math.random() * activePlayers.length); let p2Idx; do { p2Idx = Math.floor(Math.random() * activePlayers.length); } while (p1Idx === p2Idx); const p1 = activePlayers[p1Idx], p2 = activePlayers[p2Idx]; [p1.chosenAction, p2.chosenAction] = [p2.chosenAction, p1.chosenAction]; io.to(roomCode).emit('logMessage', { type: 'warning', message: `🧠 Lựa chọn của **${p1.name}** và **${p2.name}** đã bị hoán đổi!` }); startChaosPhase(roomCode); }, 3000); }
function handleBotRomanArena(roomCode, botId) { /* Tương tự handleBotAmnesia */ }
function handlePostRoundEvents(roomCode, roundWinners) { const gs = rooms[roomCode].gameState; const hasLegacyWinner = gs.roundData.decrees.some(d => d.id === 'DI_SAN_CUA_KE_THANG'); if (hasLegacyWinner && roundWinners.length > 0) { const winnerId = roundWinners[Math.floor(Math.random() * roundWinners.length)]; const winner = gs.players.find(p => p.id === winnerId); if (winner.isBot) { if (gs.decreeDeck.length < 3) shuffleDecreeDeck(gs); const choice = gs.decreeDeck[Math.floor(Math.random() * 3)]; gs.nextDecree = choice; io.to(roomCode).emit('logMessage', { type: 'info', message: `${winner.name} (Bot) đã chọn Sắc Lệnh bí mật cho vòng sau.` }); } else { /* Logic cho người chơi */ } } const W = gs.players.filter(p => p.score >= WIN_SCORE), L = gs.players.filter(p => p.score <= LOSE_SCORE); if (W.length > 0 || L.length > 0) { gs.phase = 'gameover'; io.to(roomCode).emit('gameOver', { winner: W[0], loser: L[0] }); } else { io.to(rooms[roomCode].hostId).emit('promptNextRound'); } }

io.on('connection', (socket) => { /* ... Giữ nguyên ... */ });

const PORT = process.env.PORT || 3000;
server.listen(PORT, () => { console.log(`[SERVER] Máy chủ đang lắng nghe trên cổng ${PORT}`); });